[default_config]
version = "0.9.0"
assembler = "nasm"
instruction_set = "x86-64"

[default_config.opts]
diagnostics = true
default_diagnostics = true

[[project]]
path = ""
version = "0.9.0"
assembler = "nasm"
instruction_set = "x86-64"

[project.opts]
diagnostics = true
default_diagnostics = true
