[default_config]
version = "0.9.0"
assembler = "nasm"
instruction_set = "x86-64"

[default_config.opts]
compiler = "nasm"
compile_flags_txt = ['"-f elf64"']
diagnostics = true
default_diagnostics = false
