name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get upgrade -y
        sudo apt-get install -y build-essential make nasm

    - name: Build
      run: make

    - name: Clean and debug
      run: make clean && make debug
